
server:
  port: ${PORT}

spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        # similarity 서비스 라우트
        - id: similarity
          uri: http://codify-similarity.codify.svc.cluster.local
          predicates:
            - Path=/api/similarity/**

        - id: parsing
          uri: http://codify-parsing.codify.svc.cluster.local
          predicates:
            - Path=/api/parse/**
            
        # submit 서비스 라우트
        - id: submit
          uri: http://codify-submit.codify.svc.cluster.local
          predicates:
            - Path=/api/submit/**

        - id: dashboard
          uri: http://codify-dashboard.codify.svc.cluster.local
          predicates:
            - Path=/api/dashboard/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,beans,httptrace,metrics
        exclude: env,configprops,heapdump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      enabled: true
  health:
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: ${MANAGEMENT_PORT}

