
server:
  port: ${PORT}

spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "https://codify-frontend-blush.vercel.app"
              - "https://codify-site.shop"
              - "https://www.codify-site.shop"
            allow-credentials: true
            allowed-headers:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - USER-UUID
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        # similarity 서비스 라우트
        - id: similarity
          uri: http://codify-similarity.codify.svc.cluster.local
          predicates:
            - Path=/api/similarity/**
            - Method=GET,POST,PUT,DELETE,PATCH,OPTIONS

        - id: parsing
          uri: http://codify-parsing.codify.svc.cluster.local
          predicates:
            - Path=/api/parse/**
            - Method=GET,POST,PUT,DELETE,PATCH,OPTIONS

        # submit 서비스 라우트
        - id: submit
          uri: http://codify-submit.codify.svc.cluster.local
          predicates:
            - Path=/api/submit/**
            - Method=GET,POST,PUT,DELETE,PATCH,OPTIONS

        - id: dashboard
          uri: http://codify-dashboard.codify.svc.cluster.local
          predicates:
            - Path=/api/dashboard/**
            - Method=GET,POST,PUT,DELETE,PATCH,OPTIONS

        - id: upload
          uri: http://codify-upload.codify.svc.cluster.local
          predicates:
            - Path=/api/upload/**
            - Method=GET,POST,PUT,DELETE,PATCH,OPTIONS

        - id: result
          uri: http://codify-result.codify.svc.cluster.local
          predicates:
            - Path=/api/result/**
            - Method=GET,POST,PUT,DELETE,PATCH,OPTIONS

        - id: parsing
          uri: http://codify-parsing.codify.svc.cluster.local
          predicates:
            - Path=/api/parsing/**
            - Method=GET,POST,PUT,DELETE,PATCH,OPTIONS

        - id: similarity
          uri: http://codify-similarity.codify.svc.cluster.local
          predicates:
            - Path=/api/similarity/**
            - Method=GET,POST,PUT,DELETE,PATCH,OPTIONS

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,beans,httptrace,metrics
        exclude: env,configprops,heapdump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      enabled: true
  health:
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: ${MANAGEMENT_PORT}

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG

