
server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gateway-test
          uri: lb://gateway-test  # Eureka에 등록된 서비스 이름
          predicates:
            - Path=/test/**        # 원하는 경로로 매핑

        # similarity 서비스 라우트
        - id: similarity
          uri: lb://similarity
          predicates:
            - Path=/api/similarity/**

        - id: parsing
          uri: lb://parsing
          predicates:
            - Path=/api/parse/**
            
        # submit 서비스 라우트
        - id: submit-blue
          uri: lb://submit-blue
          predicates:
            - Path=/api/submit/**
            - Header=X-Color, blue
          filters:
            - StripPrefix=2

        - id: submit-green
          uri: lb://submit-green
          predicates:
            - Path=/api/submit/**
            - Header=X-Color, green
          filters:
            - StripPrefix=2


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:8761/eureka}
      # defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

# 배포 확인을 위한 Actuator 추가
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,httpexchanges,metrics
  endpoint:
    gateway:
      enabled: true