name: gateway-ci-cd
on:
  push:
    branches: ["feature/#4/ci-cd"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build jar
        run: ./gradlew clean bootJar -x test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gateway:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gateway:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      APP_DIR: /home/gateway
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            sudo docker network ls | grep -q codify_net || sudo docker network create codify_net
            cd ${APP_DIR}
            sudo docker compose pull || true
            sudo docker compose up -d || true
            sudo docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
